const ACTION_TYPE = {
  UPDATE_PATIENT_DETAILS: "UPDATE_PATIENT_DETAILS",
  ADD_NEW_PATIENT: "ADD_NEW_PATIENT",
  ADD_PATIENT_SUCCESS: "ADD_PATIENT_SUCCESS",
  ADD_PATIENT_ERROR: "ADD_PATIENT_ERROR"
}

export default ACTION_TYPE
