const ACTION_TYPE = {
  LOGIN_USER: "LOGIN_USER",
  UPDATE_LOGIN_DETAILS: "UPDATE_LOGIN_DETAILS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_USER: "LOGOUT_USER",
}

export default ACTION_TYPE
