const ACTION_TYPE = {
  PATIENT_RECORDS_SUCCESS: "PATIENT_RECORDS_SUCCESS",
  PATIENT_RECORDS_ERROR: "PATIENT_RECORDS_ERROR",
  TOGGLE_ADD_PATIENT_MODAL: "TOGGLE_ADD_PATIENT_MODAL"
}

export default ACTION_TYPE
